// SPDX-FileCopyrightText: 2025 The Cipher Host Team <team@cipher.host>
//
// SPDX-License-Identifier: MIT

package xhttp

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"

	"go.cipher.host/x/xerrors"
)

const (
	// ErrMarshalDetailError is returned when we fail to marshal error details.
	ErrMarshalDetailError xerrors.Error = "failed to marshal error details"

	// ErrWriteDetailError is returned when we fail to write error details to an
	// HTTP response writer.
	ErrWriteDetailError xerrors.Error = "failed to encode and write error details"
)

const (
	// Default error title if http.StatusText is unavailable for a status.
	defaultErrorTitle = "Unknown Error"

	// Separator used in the Error() string representation.
	titleSeparator = ": "
)

// DetailError represents an error response that carry both machine and
// human-readable details of errors in HTTP response content. It's inspired by
// [RFC 9457], but has been greatly simplified.
//
// [RFC 9457]: https://www.rfc-editor.org/rfc/rfc9457.html
type DetailError struct {
	// Title is a short, human-readable summary of the error. If not set when
	// marshaling to JSON or generating an error string, it will be derived from
	// the Status field or a generic default.
	Title string `json:"title"`

	// Detail is a human-readable explanation specific to this occurrence of the
	// error.
	Detail string `json:"detail,omitempty"`

	// Documentation is an URI to documentation describing the error in more
	// details.
	Documentation string `json:"documentation,omitempty"`

	// RequestID is a unique identifier that identifies the request that caused
	// the error.
	RequestID string `json:"requestID,omitempty"`

	// Status is the HTTP status code generated by the origin server for this
	// occurrence of the error. While the field can be any integer, it should
	// ideally be a valid HTTP status code (typically >= 400 for errors).
	Status int `json:"status"`
}

// Error implements the Error interface. It provides a human-readable string
// representation of the error, suitable for logging or simple error messages.
//
// Example: "500: Internal Server Error: an unexpected issue occurred".
func (e *DetailError) Error() string {
	estimatedLen := 3 + len(titleSeparator)

	if e.Title != "" {
		estimatedLen += len(e.Title)
	} else {
		estimatedLen += 30
	}

	if e.Detail != "" {
		estimatedLen += len(titleSeparator) + len(e.Detail)
	}

	if e.RequestID != "" {
		estimatedLen += len(e.RequestID) + 2
	}

	var builder strings.Builder

	builder.Grow(estimatedLen)

	builder.WriteString(strconv.Itoa(e.Status))

	if e.RequestID != "" {
		builder.WriteString(" (")
		builder.WriteString(e.RequestID)
		builder.WriteString(")")
	}

	builder.WriteString(titleSeparator)

	title := e.Title

	if title == "" {
		title = http.StatusText(e.Status)

		if title == "" {
			title = defaultErrorTitle
		}
	}

	builder.WriteString(title)

	if e.Detail != "" {
		builder.WriteString(": ")
		builder.WriteString(e.Detail)
	}

	return builder.String()
}

// MarshalJSON implements the json.Marshaler interface. It ensures that if
// e.Title is empty, a title is derived from e.Status for the JSON output.
func (e *DetailError) MarshalJSON() ([]byte, error) { //nolint:unparam // needed by the interface
	alias := struct {
		Title         string `json:"title"`
		Detail        string `json:"detail,omitempty"`
		Documentation string `json:"documentation,omitempty"`
		RequestID     string `json:"requestID,omitempty"`
		Status        int    `json:"status"`
	}{
		Title:         e.Title,
		Detail:        e.Detail,
		Documentation: e.Documentation,
		RequestID:     e.RequestID,
		Status:        e.Status,
	}

	if alias.Title == "" {
		alias.Title = http.StatusText(e.Status)

		if alias.Title == "" {
			alias.Title = defaultErrorTitle
		}
	}

	data, _ := json.Marshal(alias) //nolint:errcheck // this should always be safe

	return data, nil
}

// WriteJSON serializes the DetailError to JSON and writes it to the given
// http.ResponseWriter. It sets the Content-Type header to
// "application/problem+json" and the status code to the e.Status field.
func (e *DetailError) WriteJSON(w http.ResponseWriter) error {
	w.Header().Set(HeaderKeyContentType, HeaderValueApplicationProblemJSON)

	w.WriteHeader(e.Status)

	if err := json.NewEncoder(w).Encode(e); err != nil {
		return fmt.Errorf("%w: %w", ErrWriteDetailError, err)
	}

	return nil
}
