// SPDX-FileCopyrightText: 2025 The Cipher Host Team <team@cipher.host>
//
// SPDX-License-Identifier: MIT

package xhttp

// Common HTTP header keys. Copied from [pkg/net/http/header.go] for
// convenience.
//
// [pkg/net/http/header.go]: https://github.com/go-playground/pkg/blob/master/net/http/headers.go
const (
	HeaderKeyAge                           string = "Age"
	HeaderKeyAltSCV                        string = "Alt-Svc"
	HeaderKeyAccept                        string = "Accept"
	HeaderKeyAcceptCharset                 string = "Accept-Charset"
	HeaderKeyAcceptPatch                   string = "Accept-Patch"
	HeaderKeyAcceptRanges                  string = "Accept-Ranges"
	HeaderKeyAcceptedLanguage              string = "Accept-Language"
	HeaderKeyAcceptEncoding                string = "Accept-Encoding"
	HeaderKeyAuthorization                 string = "Authorization"
	HeaderKeyCrossOriginResourcePolicy     string = "Cross-Origin-Resource-Policy"
	HeaderKeyCacheControl                  string = "Cache-Control"
	HeaderKeyConnection                    string = "Connection"
	HeaderKeyContentDisposition            string = "Content-Disposition"
	HeaderKeyContentEncoding               string = "Content-Encoding"
	HeaderKeyContentLength                 string = "Content-Length"
	HeaderKeyContentType                   string = "Content-Type"
	HeaderKeyContentLanguage               string = "Content-Language"
	HeaderKeyContentLocation               string = "Content-Location"
	HeaderKeyContentRange                  string = "Content-Range"
	HeaderKeyDate                          string = "Date"
	HeaderKeyDeltaBase                     string = "Delta-Base"
	HeaderKeyETag                          string = "ETag"
	HeaderKeyExpires                       string = "Expires"
	HeaderKeyHost                          string = "Host"
	HeaderKeyIM                            string = "IM"
	HeaderKeyIfMatch                       string = "If-Match"
	HeaderKeyIfModifiedSince               string = "If-Modified-Since"
	HeaderKeyIfNoneMatch                   string = "If-None-Match"
	HeaderKeyIfRange                       string = "If-Range"
	HeaderKeyIfUnmodifiedSince             string = "If-Unmodified-Since"
	HeaderKeyKeepAliveK                    string = "Keep-Alive"
	HeaderKeyLastModified                  string = "Last-Modified"
	HeaderKeyLink                          string = "Link"
	HeaderKeyPragma                        string = "Pragma"
	HeaderKeyProxyAuthenticate             string = "Proxy-Authenticate"
	HeaderKeyProxyAuthorization            string = "Proxy-Authorization"
	HeaderKeyPublicKeyPins                 string = "Public-Key-Pins"
	HeaderKeyRequestID                     string = "Request-Id"
	HeaderKeyRetryAfter                    string = "Retry-After"
	HeaderKeyReferer                       string = "Referer"
	HeaderKeyServer                        string = "Server"
	HeaderKeySetCookie                     string = "Set-Cookie"
	HeaderKeyStrictTransportSecurity       string = "Strict-Transport-Security"
	HeaderKeyTrailer                       string = "Trailer"
	HeaderKeyTK                            string = "Tk"
	HeaderKeyTransferEncoding              string = "Transfer-Encoding"
	HeaderKeyLocation                      string = "Location"
	HeaderKeyUpgrade                       string = "Upgrade"
	HeaderKeyVary                          string = "Vary"
	HeaderKeyVia                           string = "Via"
	HeaderKeyWarning                       string = "Warning"
	HeaderKeyWWWAuthenticate               string = "WWW-Authenticate"
	HeaderKeyXForwardedFor                 string = "X-Forwarded-For"
	HeaderKeyXForwardedHost                string = "X-Forwarded-Host"
	HeaderKeyXForwardedProto               string = "X-Forwarded-Proto"
	HeaderKeyXRealIP                       string = "X-Real-Ip"
	HeaderKeyXContentTypeOptions           string = "X-Content-Type-Options"
	HeaderKeyXFrameOptions                 string = "X-Frame-Options"
	HeaderKeyXXSSProtection                string = "X-XSS-Protection"
	HeaderKeyXDNSPrefetchControl           string = "X-DNS-Prefetch-Control"
	HeaderKeyAllow                         string = "Allow"
	HeaderKeyOrigin                        string = "Origin"
	HeaderKeyAccessControlAllowOrigin      string = "Access-Control-Allow-Origin"
	HeaderKeyAccessControlAllowCredentials string = "Access-Control-Allow-Credentials"
	HeaderKeyAccessControlAllowHeaders     string = "Access-Control-Allow-Headers"
	HeaderKeyAccessControlAllowMethods     string = "Access-Control-Allow-Methods"
	HeaderKeyAccessControlExposeHeaders    string = "Access-Control-Expose-Headers"
	HeaderKeyAccessControlMaxAge           string = "Access-Control-Max-Age"
	HeaderKeyAccessControlRequestHeaders   string = "Access-Control-Request-Headers"
	HeaderKeyAccessControlRequestMethod    string = "Access-Control-Request-Method"
	HeaderKeyTimingAllowOrigin             string = "Timing-Allow-Origin"
	HeaderKeyUserAgent                     string = "User-Agent"
)

// Common HTTP header values.
const (
	HeaderValueNoCache                string = "no-cache"
	HeaderValueKeepAliveV             string = "keep-alive"
	HeaderValueClose                  string = "close"
	HeaderValueApplicationJSON        string = "application/json"
	HeaderValueApplicationProblemJSON string = "application/problem+json"
	HeaderValueFormData               string = "multipart/form-data"
	HeaderValueTextHTML               string = "text/html"
	HeaderValueTextPlain              string = "text/plain"
	HeaderValueTextCSS                string = "text/css"
	HeaderValueTextJavascript         string = "text/javascript"
	HeaderValueApplicationJavascript  string = "application/javascript"
	HeaderValueApplicationXML         string = "application/xml"
	HeaderValueImageJPEG              string = "image/jpeg"
	HeaderValueImagePNG               string = "image/png"
	HeaderValueImageGIF               string = "image/gif"
	HeaderValueImageSVG               string = "image/svg+xml"
	HeaderValueCharsetUTF8            string = "charset=utf-8"
	HeaderValueGzip                   string = "gzip"
	HeaderValueDeflate                string = "deflate"
	HeaderValueBrotli                 string = "br"
	HeaderValueWildcard               string = "*"
	HeaderValueSameOrigin             string = "same-origin"
	HeaderValueDeny                   string = "deny"
	HeaderValueSameSiteLax            string = "Lax"
	HeaderValueSameSiteStrict         string = "Strict"
	HeaderValueSameSiteNone           string = "None"
	HeaderValueSecure                 string = "secure"
	HeaderValueNoTransform            string = "no-transform"
	HeaderValueChunked                string = "chunked"
	HeaderValueTrue                   string = "true"
	HeaderValueFalse                  string = "false"
)
